name: wss
description: WHK Subdomains Scanner
version: 1.0.0
repository: https://github.com/yhojann-cl/dart-cli-subdomain-scanner

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  dictlib: ^1.0.1
  dnslib: ^1.0.2
  http: ^1.4.0
  intl: ^0.20.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
